/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVivaRouteImport } from './routes/_app.viva'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportCardRouteImport } from './routes/_app.report-card'
import { Route as AppPlagiarismRouteImport } from './routes/_app.plagiarism'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMentorshipRouteImport } from './routes/_app.mentorship'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppDissertationRouteImport } from './routes/_app.dissertation'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAiAnalysisRouteImport } from './routes/_app.ai-analysis'
import { Route as AppDissertationIndexRouteImport } from './routes/_app.dissertation.index'
import { Route as AppDissertationNewRouteImport } from './routes/_app.dissertation.new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVivaRoute = AppVivaRouteImport.update({
  id: '/viva',
  path: '/viva',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportCardRoute = AppReportCardRouteImport.update({
  id: '/report-card',
  path: '/report-card',
  getParentRoute: () => AppRoute,
} as any)
const AppPlagiarismRoute = AppPlagiarismRouteImport.update({
  id: '/plagiarism',
  path: '/plagiarism',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorshipRoute = AppMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppDissertationRoute = AppDissertationRouteImport.update({
  id: '/dissertation',
  path: '/dissertation',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAnalysisRoute = AppAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppDissertationIndexRoute = AppDissertationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDissertationRoute,
} as any)
const AppDissertationNewRoute = AppDissertationNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDissertationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-analysis': typeof AppAiAnalysisRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/dissertation': typeof AppDissertationRouteWithChildren
  '/meetings': typeof AppMeetingsRoute
  '/mentorship': typeof AppMentorshipRoute
  '/notifications': typeof AppNotificationsRoute
  '/plagiarism': typeof AppPlagiarismRoute
  '/report-card': typeof AppReportCardRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
  '/users': typeof AppUsersRoute
  '/viva': typeof AppVivaRoute
  '/dissertation/new': typeof AppDissertationNewRoute
  '/dissertation/': typeof AppDissertationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-analysis': typeof AppAiAnalysisRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/meetings': typeof AppMeetingsRoute
  '/mentorship': typeof AppMentorshipRoute
  '/notifications': typeof AppNotificationsRoute
  '/plagiarism': typeof AppPlagiarismRoute
  '/report-card': typeof AppReportCardRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
  '/users': typeof AppUsersRoute
  '/viva': typeof AppVivaRoute
  '/dissertation/new': typeof AppDissertationNewRoute
  '/dissertation': typeof AppDissertationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/ai-analysis': typeof AppAiAnalysisRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dissertation': typeof AppDissertationRouteWithChildren
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/mentorship': typeof AppMentorshipRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/plagiarism': typeof AppPlagiarismRoute
  '/_app/report-card': typeof AppReportCardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/viva': typeof AppVivaRoute
  '/_app/dissertation/new': typeof AppDissertationNewRoute
  '/_app/dissertation/': typeof AppDissertationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/ai-analysis'
    | '/chat'
    | '/dashboard'
    | '/dissertation'
    | '/meetings'
    | '/mentorship'
    | '/notifications'
    | '/plagiarism'
    | '/report-card'
    | '/settings'
    | '/timeline'
    | '/users'
    | '/viva'
    | '/dissertation/new'
    | '/dissertation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/ai-analysis'
    | '/chat'
    | '/dashboard'
    | '/meetings'
    | '/mentorship'
    | '/notifications'
    | '/plagiarism'
    | '/report-card'
    | '/settings'
    | '/timeline'
    | '/users'
    | '/viva'
    | '/dissertation/new'
    | '/dissertation'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/ai-analysis'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/dissertation'
    | '/_app/meetings'
    | '/_app/mentorship'
    | '/_app/notifications'
    | '/_app/plagiarism'
    | '/_app/report-card'
    | '/_app/settings'
    | '/_app/timeline'
    | '/_app/users'
    | '/_app/viva'
    | '/_app/dissertation/new'
    | '/_app/dissertation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/viva': {
      id: '/_app/viva'
      path: '/viva'
      fullPath: '/viva'
      preLoaderRoute: typeof AppVivaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report-card': {
      id: '/_app/report-card'
      path: '/report-card'
      fullPath: '/report-card'
      preLoaderRoute: typeof AppReportCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plagiarism': {
      id: '/_app/plagiarism'
      path: '/plagiarism'
      fullPath: '/plagiarism'
      preLoaderRoute: typeof AppPlagiarismRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentorship': {
      id: '/_app/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof AppMentorshipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dissertation': {
      id: '/_app/dissertation'
      path: '/dissertation'
      fullPath: '/dissertation'
      preLoaderRoute: typeof AppDissertationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-analysis': {
      id: '/_app/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AppAiAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dissertation/': {
      id: '/_app/dissertation/'
      path: '/'
      fullPath: '/dissertation/'
      preLoaderRoute: typeof AppDissertationIndexRouteImport
      parentRoute: typeof AppDissertationRoute
    }
    '/_app/dissertation/new': {
      id: '/_app/dissertation/new'
      path: '/new'
      fullPath: '/dissertation/new'
      preLoaderRoute: typeof AppDissertationNewRouteImport
      parentRoute: typeof AppDissertationRoute
    }
  }
}

interface AppDissertationRouteChildren {
  AppDissertationNewRoute: typeof AppDissertationNewRoute
  AppDissertationIndexRoute: typeof AppDissertationIndexRoute
}

const AppDissertationRouteChildren: AppDissertationRouteChildren = {
  AppDissertationNewRoute: AppDissertationNewRoute,
  AppDissertationIndexRoute: AppDissertationIndexRoute,
}

const AppDissertationRouteWithChildren = AppDissertationRoute._addFileChildren(
  AppDissertationRouteChildren,
)

interface AppRouteChildren {
  AppAiAnalysisRoute: typeof AppAiAnalysisRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDissertationRoute: typeof AppDissertationRouteWithChildren
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMentorshipRoute: typeof AppMentorshipRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlagiarismRoute: typeof AppPlagiarismRoute
  AppReportCardRoute: typeof AppReportCardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVivaRoute: typeof AppVivaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAnalysisRoute: AppAiAnalysisRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDissertationRoute: AppDissertationRouteWithChildren,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMentorshipRoute: AppMentorshipRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlagiarismRoute: AppPlagiarismRoute,
  AppReportCardRoute: AppReportCardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppUsersRoute: AppUsersRoute,
  AppVivaRoute: AppVivaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
